### ISSUE TITLE
Make this a W3C Note

### ISSUE THREAD

**Issue by rtoy** [WebAudio/Audio-EQ-Cookbook#11]
It came up in the review of the V1 proposed recommendation that the link to the cookbook pointed here instead of some canonical place in the W3C website.  The proposal from @svgeesus is to make this an official W3C Note so that there's a stable link.

This also means the spec can reference a fixed version of the cookbook in case changes are made to the formulas that are incompatible or inconsistent with previous versions.  That seems unlikely, but, but not impossible.  Robert Brirstow-Johnson has reviewed the latest version for correctness.

**Comment by rtoy** [comment]
WebAudio F2F 2021 meeting:  It was resolved to make this an official W3C Note:  https://lists.w3.org/Archives/Public/public-audio/2021AprJun/0020.html

**Comment by svgeesus** [comment]
[Published 8 Jun 2021](https://www.w3.org/TR/2021/NOTE-audio-eq-cookbook-20210608/)
